# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WWDaily' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WWDaily
pod 'AFNetworking', '~> 3.2.1'
pod 'SDWebImage', '~> 4.4.2'
pod 'MBProgressHUD', '~> 1.1.0'
 pod 'SVProgressHUD', '~> 2.2.5'

  target 'WWDailyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WWDailyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
